import type {Metadata} from "next";
import {PT_Sans} from "next/font/google";
import "./globals.css";
import React from "react";
import {Header} from "@/widgets/header";

const ptSans = PT_Sans({preload: false, weight: '400'});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};


export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={ptSans.className}>
        <Header/>
        {children}
        </body>
        </html>
    );
}
